Repository hummingbird-me/kitsu-mobile, pull requests merged in 2018-03, with the labels that each got.

#300 Use user title preference
  src/config/api.js
  src/config/middlewares.js
  src/screens/Search/Lists/ResultsList.js
  src/screens/Search/SearchScreen/index.js
  src/utils/getTitleField.js
Labels: Mergeable

#299 Limit about TextInput to 500 ch.
  src/screens/Profiles/components/EditModal/component.js
Labels: Mergeable

#297 Empty states for library
  src/assets/img/library/index.js
  src/assets/img/library/mystery.png
  src/assets/img/library/oh-no.png
  src/screens/Profiles/UserLibrary/components/LibraryEmptyState/component.js
  src/screens/Profiles/UserLibrary/components/LibraryEmptyState/index.js
  src/screens/Profiles/UserLibrary/components/LibraryEmptyState/styles.js
  src/screens/Profiles/UserLibrary/components/UserLibraryList/component.js
  src/screens/Profiles/UserLibrary/index.js
  src/screens/Search/SearchResults.js
Labels: Mergeable

#301 [Fix] Quick fixes
  src/screens/Profiles/UserLibrary/components/UserLibraryList/component.js
  src/screens/Search/SearchResults.js
  src/screens/Sidebar/SidebarScreen.js
  src/store/anime/actions.js
  src/store/auth/actions.js
  src/store/auth/reducer.js
  src/store/profile/actions.js
Labels: reviewed

#305 [Fix]6.5 Crash fixes
  src/App.js
  src/screens/Profiles/UserLibrary/components/LibraryEmptyState/component.js
  src/screens/Sidebar/Library/ExportLibrary.js
  src/store/auth/actions.js
Labels: reviewed

#307 [Fix] Bug fixes
  android/build.gradle
  src/components/Rating/component.js
  src/config/middlewares.js
  src/screens/Auth/SplashScreen.js
  src/screens/Feed/components/PostImage/component.js
  src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js
  src/screens/Sidebar/SidebarScreen.js
  src/store/auth/actions.js
  src/store/auth/reducer.js
  src/store/user/actions.js
Labels: reviewed

#308 Fix bugs
  src/components/ContentList/component.js
  src/routes/common.js
  src/routes/feed.js
  src/routes/library.js
  src/screens/Search/Lists/TopsList/index.js
  src/screens/Search/SearchScreen/index.js
Labels: reviewed

#314 [Fix]Minor bug fixes
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-1024.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-120.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-121.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-152.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-167.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-180.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-20.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-29.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-40.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-41.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-42.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-58.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-59.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-60.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-76.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-80.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-81.png
  ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Icon-87.png
  src/routes/library.js
  src/routes/sidebar.js
  src/screens/Auth/AuthScreen.js
  src/screens/Intro/RegistrationScreen.js
  src/screens/Library/LibraryScreen/component.js
  src/screens/Onboarding/Aozora/WelcomeScreen.js
  src/screens/Onboarding/common/RatingSystemScreen.js
  src/screens/Sidebar/Library/LibraryScreen.js
  src/screens/Sidebar/Library/LibrarySettings/component.js
  src/screens/Sidebar/Library/LibrarySettings/index.js
  src/screens/Sidebar/Library/LibrarySettings/sortOptions.js
  src/screens/Sidebar/Library/LibrarySettings/styles.js
  src/screens/Sidebar/Library/index.js
  src/screens/Sidebar/LinkedAccounts.js
  src/screens/Sidebar/common/SidebarHeader.js
  src/screens/Sidebar/index.js
  src/store/profile/actions.js
  src/store/user/actions.js
Labels: reviewed

#316 [Fix]Properly logout users from facebook sdk.
  src/screens/Auth/AuthScreen.js
  src/screens/Intro/RegistrationScreen.js
  src/screens/Sidebar/LinkedAccounts.js
  src/store/auth/actions.js
Labels: reviewed

#318 Disable drawer on sub-routes
  src/routes/tabs.js
Labels: reviewed

#323 Post Editing/Deleting
  src/screens/Feed/components/Post/component.js
  src/screens/Feed/components/Post/components/PostHeader/component.js
  src/screens/Feed/pages/PostCreation/CreatePost.js
  src/store/user/actions.js
Labels: needs-review

#320 Scroll library tabs
  src/screens/Library/LibraryScreen/component.js
  src/screens/Library/LibraryScreen/tabbar.js
  src/screens/Profiles/components/TabBar/component.js
Labels: needs-review
